cmake_minimum_required(VERSION 3.16)
project(flawk_publisher LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(PkgConfig REQUIRED)
pkg_check_modules(MEDIA REQUIRED IMPORTED_TARGET libavformat libavcodec libavutil json-c)
find_package(Threads REQUIRED)
add_executable(flawk-publisher main.cpp)
target_link_libraries(flawk-publisher PRIVATE PkgConfig::MEDIA Threads::Threads)
target_compile_options(flawk-publisher PRIVATE -Wall -Wextra -Werror -Wno-unused-function)
